import type { Metadata } from 'next';
import { Suspense } from 'react';
import EnterpriseReviewForm from './EnterpriseReviewForm';

export const metadata: Metadata = {
  title: 'Security Review Recommended — CyberShield Enterprise',
  description:
    'Request an automated security review for your domain. Responses generated by the CyberShield Security Intelligence Engine.',
};

export default function EnterpriseReviewPage() {
  return (
    <Suspense fallback={<div className="min-h-screen bg-[#0a0f1e]" />}>
      <EnterpriseReviewForm />
    </Suspense>
  );
}
