export interface OutreachInput {
  businessName: string;
  website: string;
  industry?: string;
  city?: string;
  scanScore?: number;
  riskLevel?: string;
  issues?: string[];
  contactName?: string;
}

export type OutreachType =
  | 'cold_email'
  | 'linkedin'
  | 'facebook'
  | 'follow_up'
  | 'agency_pitch'
  | 'audit_summary';

const TEMPLATES: Record<OutreachType, (input: OutreachInput) => string> = {
  cold_email: (i) => `Subject: Quick security note for ${i.businessName}

Hi${i.contactName ? ` ${i.contactName}` : ''},

I ran a quick security check on ${i.website} and noticed ${i.issues?.length ? `several areas worth addressing (${i.issues.slice(0, 2).join(', ')})` : 'some configuration gaps'}.

CyberShield helps ${i.industry ?? 'businesses'} in ${i.city ?? 'your area'} monitor website security continuously — not just one-time scans.

Would a 15-minute walkthrough be useful this week?

Best,
[Your name]
CyberShield`,

  linkedin: (i) => `Hi — I help ${i.industry ?? 'local businesses'} protect their websites from security blind spots.

I noticed ${i.businessName}'s site (${i.website}) could benefit from continuous monitoring${i.riskLevel ? ` — current risk level: ${i.riskLevel}` : ''}.

Happy to share a free audit summary if useful.`,

  facebook: (i) => `Hey ${i.businessName} team 👋

We work with ${i.industry ?? 'local businesses'} on website security. Quick scan of ${i.website} showed room for improvement.

DM me if you'd like a free security snapshot — no pitch, just value.`,

  follow_up: (i) => `Hi${i.contactName ? ` ${i.contactName}` : ''},

Following up on the security note for ${i.businessName}. ${i.scanScore !== undefined ? `Your site scored ${i.scanScore}/100` : 'The initial scan flagged actionable items'}.

Still happy to walk through fixes — takes about 15 minutes.

Best,
[Your name]`,

  agency_pitch: (i) => `Partnership opportunity — CyberShield white-label security monitoring

Target: ${i.businessName} (${i.website})
Industry: ${i.industry ?? 'General'}
Market: ${i.city ?? 'Regional'}

Offer: Add recurring security monitoring to your agency stack. We handle scans, alerts, and client reports — you keep the relationship.

Revenue share available. Let's connect.`,

  audit_summary: (i) => `SECURITY AUDIT SUMMARY
━━━━━━━━━━━━━━━━━━━━
Business: ${i.businessName}
Website: ${i.website}
${i.scanScore !== undefined ? `Score: ${i.scanScore}/100` : ''}
${i.riskLevel ? `Risk Level: ${i.riskLevel.toUpperCase()}` : ''}

KEY FINDINGS:
${(i.issues ?? ['No critical issues detected in initial scan']).map((issue, idx) => `${idx + 1}. ${issue}`).join('\n')}

RECOMMENDED ACTIONS:
• Enable continuous SSL & header monitoring
• Set up automated weekly scans
• Configure alert notifications for score drops

Generated by CyberShield Founder OS`,
};

export function generateOutreach(type: OutreachType, input: OutreachInput): string {
  return TEMPLATES[type](input);
}

export const OUTREACH_TYPES: { id: OutreachType; label: string }[] = [
  { id: 'cold_email', label: 'Cold Email' },
  { id: 'linkedin', label: 'LinkedIn Message' },
  { id: 'facebook', label: 'Facebook DM' },
  { id: 'follow_up', label: 'Follow-up' },
  { id: 'agency_pitch', label: 'Agency Pitch' },
  { id: 'audit_summary', label: 'Audit Summary' },
];
