import type { Metadata } from 'next';
import { Suspense } from 'react';
import EnterpriseLeadForm from './EnterpriseLeadForm';

export const metadata: Metadata = {
  title: 'Automated Enterprise Security Review',
  description:
    'Submit your domain for automated security analysis. Responses generated by the CyberShield Security Intelligence Engine — no phone call required.',
};

export default function EnterpriseLeadPage() {
  return (
    <Suspense fallback={<div className="min-h-screen bg-[#0a0f1e]" />}>
      <EnterpriseLeadForm />
    </Suspense>
  );
}
